### ISSUE TITLE
Ampersand as a key breaks things

### ISSUE THREAD

**Issue by GitSkunk** [kencx/keyb#9]
Setting an entry with an & as the key breaks the loading of the keymap. You can escape it with \&, but the slash shows up in the key display.

**Comment by kencx** [comment]
Wrap it with single or double quotes. It should work without escaping:

```yaml
- name: example
  keybinds:
    - name: foo
      key: "super + &"
```
